# Generated by Django 5.0.2 on 2024-02-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0002_alter_book_quantity_in_stock_customuser'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
