# Generated by Django 5.0.2 on 2024-02-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0003_rename_customuser_user'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
